// *** GET DATA FROM FIRESTORE

import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/section/Header";
import Feed from "../components/section/Feed";
import { collection, query, orderBy, getDocs } from "firebase/firestore";
import { db } from "../firebase";
import { GetServerSideProps } from "next";

type post = {
  id: string;
  image: string;
  imagePost: string;
  name: string;
  caption: string;
};

const Home: NextPage<{ posts: post[] }> = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-50/50">
        {/* Header */}
        <Header />
        {/* Feed: Stories, Posts,     Suggestion */}
        <Feed posts={props.posts} />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const q = query(collection(db, "posts"), orderBy("timestamp", "desc"));

  const querySnapshot = await getDocs(q);
  const postsFromDB = querySnapshot.docs.map((doc) => {
    return {
      id: doc.id,
      image: doc.data().image,
      imagePost: doc.data().imageLink,
      name: doc.data().username,
      caption: doc.data().caption,
    };
  });

  return {
    props: {
      posts: postsFromDB,
    },
  };
};

export default Home;
